FROM auto-setup-build

RUN useradd -m python_user
# RUN ln -s /proc/self/fd /dev/fd

WORKDIR /home/python_user
USER python_user
RUN curl https://pyenv.run | bash

ENV HOME  /home/python_user
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN echo 'export PATH="'${HOME}'/.pyenv/bin:'${PATH}'"' >> ~/.zshrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.zshrc
RUN zsh -c "pyenv install 3.7.9 && \
            pyenv global 3.7.9 && \
            pip install notebook"

WORKDIR ${HOME}/app
ENTRYPOINT [ "/bin/zsh", "-c"]
