FROM auto-setup-build

# RUN useradd -m python_user
# RUN ln -s /proc/self/fd /dev/fd

# WORKDIR /home/python_user
WORKDIR /root
# USER python_user
USER root
RUN curl https://pyenv.run | bash

# ENV HOME  /home/python_user
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN echo 'export PATH="'${HOME}'/.pyenv/bin:'${PATH}'"' >> ~/.zshrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.zshrc
RUN zsh -c ". /root/.zshrc && pyenv install 3.7.9 && pyenv virtualenv 3.7.9 py37 && pyenv rehash"
RUN zsh -c ". /root/.zshrc && pyenv activate py37 && pip install notebook"

ENTRYPOINT [ "/bin/zsh", "-c"]
